### ISSUE TITLE
Code review issue from Emil

### ISSUE THREAD

**Issue by emil0519** [athenacheng15/91APP-program-cowork#6]
_**Layout**_

- [x] Header有些按鈕沒有cursor-pointer，如商品分類,latest product，繁體中文等
- [x] 輪播圖右側能夠按的圖片及標題沒有cursor-pointer
- [x] 在Safari桌機版正常螢幕寬度中（沒有接大螢幕），可以稍微向右邊移動，
- [x] 在Safari正常螢幕寬度（沒有接大螢幕），網頁的最右邊會有白邊

**Comment by athenacheng15** [comment]
send pull request
