### ISSUE TITLE
register page review from Yuchun

### ISSUE THREAD

**Issue by athenacheng15** [athenacheng15/91APP-program-cowork#7]
### register page
1. container須設定min-width及max-width，或是給文字區域一個指定的寬高值避免跑版
2. 活動流程背景padding bottom有點大
3. 『確認驗證通過』字體為橘色
4. 預約說明內容，web字體大小14px 手機12px

### reg page
1. 『*登記手機號碼需與會員手機號碼相同...』斷落雨上面輸入框要有padding

### selection page
1. 圖片比例跑掉
5. advance ( alert or 直接顯示提醒文字)
6. container要給固定寬度

### other
1. page2-page4 background color

**Comment by emil0519** [comment]
再檢查規章的字體大小

**Comment by athenacheng15** [comment]
ok!
